python3 train.py --data "datasets/300WLP"\
                 --snapshot 1\
                 --epochs 1000\
                 --workers 4\
                 --train-batch 32\
                 --val-batch 64\
                 --checkpoint "cp"\
                 --netType FAN\
                 --config_path './config/FAN.yaml' \
                 --model_size 'TINY' \
                 --pointType 3D\
                 --lr 1e-4